import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import styled from 'styled-components';

const AvoidSSRBubbles = dynamic(
  async () => (await import('@@/components/atoms/Square/Bubbles')).Bubbles,
  { ssr: false }
);

const Container = styled.div`
  min-height: 100vh;
  padding: 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const PageBubbles: NextPage = () => {
  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Container>
        <div className="App">
          <AvoidSSRBubbles />
        </div>
      </Container>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default PageBubbles;
